name: I Love Pihu

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    
jobs:
  
  MySecondJob:
   
    runs-on: ubuntu-latest

    
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo We are learning GA.
