name: I Love Pihu

on:
  workflow_dispatch:
    
jobs:
  
  MySecondJob:
   
    runs-on: ubuntu-latest

    
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo We are learning GA.
